# Generated by Django 5.2.4 on 2026-03-30 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=100)),
                ('bssid', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=100)),
                ('encryption', models.CharField(max_length=50)),
                ('rssi', models.IntegerField()),
                ('channel', models.IntegerField()),
                ('is_suspicious_name', models.BooleanField(default=False)),
                ('duplicate_count', models.IntegerField(default=1)),
                ('is_evil_twin', models.BooleanField(default=False)),
                ('classification', models.CharField(max_length=20)),
                ('risk_score', models.FloatField(default=0)),
                ('trust_score', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('access_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.accesspoint')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scanner.scansession')),
            ],
        ),
    ]
