# Generated by Django 5.2.4 on 2026-04-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkobservation',
            name='ml_classification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
