# Generated by Django 5.2.4 on 2026-04-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_simulationsession_simulationresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulationsession',
            old_name='timestamp',
            new_name='started_at',
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='simulationresult',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('stopped', 'Stopped')], default='active', max_length=10),
        ),
    ]
