# Generated by Django 5.2.4 on 2026-04-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_rename_timestamp_simulationsession_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationsession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='simulationresult',
            name='risk_level',
            field=models.CharField(default='High', max_length=20),
        ),
    ]
